language: python
sudo: true
python:
  - 2.7
  - 3.4
  - 3.5
env:
  - DJANGO="Django>=1.6.0,<1.7.0"
  - DJANGO="Django>=1.7.0,<1.8.0"
  - DJANGO="Django>=1.8.0,<1.9.0"
  - DJANGO="Django>=1.9.0,<1.10.0"
matrix:
  exclude:
    - python: 3.5
      env: DJANGO="Django>=1.6.0,<1.7.0"
    - python: 3.5
      env: DJANGO="Django>=1.7.0,<1.8.0"
    - python: 3.5
      env: DJANGO="Django>=1.8.0,<1.9.0"
before_install:
  - "git clone git://github.com/n1k0/casperjs.git"
  - "sudo ln -s `pwd`/casperjs/bin/casperjs /usr/local/bin"
install: pip install $DJANGO
script: make test
