language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
env:
  - DJANGO="Django>=1.7.0,<1.8.0"
  - DJANGO="Django>=1.8.0,<1.9.0"
  - DJANGO="Django>=1.9.0,<1.10.0"
matrix:
  exclude:
    - python: 3.5
      env: DJANGO="Django>=1.7.0,<1.8.0"
    - python: 3.5
      env: DJANGO="Django>=1.8.0,<1.9.0"
before_install:
  - "git clone --branch 1.1-beta5 git://github.com/n1k0/casperjs.git"
  - "mkdir -p node_modules/.bin"
  - "ln -s `pwd`/casperjs/bin/casperjs node_modules/.bin"
install: pip install $DJANGO
script: make test
